import http from 'node:http';import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import {fileURLToPath} from 'node:url';
const __dirname=path.dirname(fileURLToPath(import.meta.url));const root=path.resolve(__dirname,'..');
loadEnv(path.join(root,'.env'));
const DATA_DIR=process.env.DATA_DIR||path.join(root,'data');const uploads=process.env.UPLOADS_DIR||path.join(root,'public','uploads');const dbFile=path.join(DATA_DIR,'db.json');
fs.mkdirSync(DATA_DIR,{recursive:true});fs.mkdirSync(uploads,{recursive:true});
const seedFile=path.join(root,'data','db.seed.json');if(!fs.existsSync(dbFile)&&fs.existsSync(seedFile))fs.copyFileSync(seedFile,dbFile);if(fs.existsSync(dbFile)&&fs.existsSync(seedFile)){try{const db=JSON.parse(fs.readFileSync(dbFile,'utf8'));const seed=JSON.parse(fs.readFileSync(seedFile,'utf8'));let changed=false;for(const [key,value] of Object.entries(seed)){if(!(key in db)){db[key]=value;changed=true;continue}if(key==='attractions'&&Array.isArray(value)&&Array.isArray(db[key])){const byId=new Map(db[key].map(x=>[x.id,x]));for(const item of value){const cur=byId.get(item.id);if(!cur){db[key].push(item);changed=true;continue}const patch={};for(const field of ['image_url','image_status','image_authorized','image_source_note','content_status','source_record','category_label']){if(item[field]&&cur[field]!==item[field])patch[field]=item[field]}if(Object.keys(patch).length){Object.assign(cur,patch);changed=true}}}}if(changed)fs.writeFileSync(dbFile,JSON.stringify(db,null,2))}catch(e){console.error('seed migration failed',e)}}
const PORT=Number(process.env.PORT||8787);const ADMIN_TOKEN=process.env.ADMIN_TOKEN||'sumare-admin-dev';
const read=()=>JSON.parse(fs.readFileSync(dbFile,'utf8'));const write=db=>fs.writeFileSync(dbFile,JSON.stringify(db,null,2));const id=()=>crypto.randomUUID();
const send=(res,status,data,headers={})=>{res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'Content-Type, X-Admin-Token','Access-Control-Allow-Methods':'GET,POST,PUT,DELETE,OPTIONS',...headers});res.end(data===null?'':JSON.stringify(data))};
const body=req=>new Promise((resolve,reject)=>{let d='';req.on('data',c=>{d+=c;if(d.length>12000000)reject(new Error('payload too large'))});req.on('end',()=>{try{resolve(d?JSON.parse(d):{})}catch(e){reject(e)}})});const admin=req=>req.headers['x-admin-token']===ADMIN_TOKEN;
const server=http.createServer(async(req,res)=>{try{const u=new URL(req.url,`http://${req.headers.host}`);if(req.method==='OPTIONS')return send(res,204,null);if(u.pathname==='/api/health'&&req.method==='GET')return send(res,200,{ok:true,service:'conheca-sumare-api'});if(u.pathname.startsWith('/uploads/')){const p=path.join(uploads,path.basename(u.pathname));if(!fs.existsSync(p)){res.writeHead(404);return res.end()}const ext=path.extname(p).toLowerCase();const mime={'.jpg':'image/jpeg','.jpeg':'image/jpeg','.png':'image/png','.webp':'image/webp','.gif':'image/gif','.svg':'image/svg+xml'}[ext]||'application/octet-stream';res.writeHead(200,{'Content-Type':mime,'Cache-Control':'public, max-age=31536000, immutable','Access-Control-Allow-Origin':'*'});return fs.createReadStream(p).pipe(res)}
if(u.pathname==='/api/auth/login'&&req.method==='POST'){const b=await body(req);return b.token===ADMIN_TOKEN?send(res,200,{ok:true}):send(res,401,{error:'Token inválido'})}
if(u.pathname==='/api/admin/stats'&&req.method==='GET'){if(!admin(req))return send(res,401,{error:'Não autorizado'});const db=read();return send(res,200,{attractions:db.attractions.length,hotels:db.hotels.length,events:db.events.length,officialSources:(db.official_sources||[]).filter(x=>x.active!==false).length,pendingSubmissions:db['event-submissions'].filter(x=>x.status==='pending').length})}
if(u.pathname==='/api/uploads'&&req.method==='POST'){if(!admin(req))return send(res,401,{error:'Não autorizado'});const b=await body(req);if(!b.data||!b.name)return send(res,400,{error:'Arquivo inválido'});const ext=path.extname(b.name).toLowerCase()||'.bin';const safe=`${Date.now()}-${crypto.randomBytes(5).toString('hex')}${ext}`;fs.writeFileSync(path.join(uploads,safe),Buffer.from(b.data,'base64'));return send(res,201,{url:`/uploads/${safe}`})}
const parts=u.pathname.split('/').filter(Boolean);if(parts[0]!=='api')return send(res,404,{error:'Não encontrado'});const resource=parts[1],rid=parts[2],action=parts[3];const db=read();if(!Array.isArray(db[resource]))return send(res,404,{error:'Recurso não encontrado'});
if(resource==='event-submissions'&&rid&&action&&req.method==='POST'){if(!admin(req))return send(res,401,{error:'Não autorizado'});const idx=db[resource].findIndex(x=>x.id===rid);if(idx<0)return send(res,404,{error:'Submissão não encontrada'});const b=await body(req);if(action==='approve'){const s=db[resource][idx];if(s.status!=='pending')return send(res,409,{error:'Submissão já revisada'});const event={id:id(),name:s.name,description:s.description,date_start:s.date_start,date_end:s.date_end,location:s.location,category:s.category,free_entry:!!s.free_entry,featured:false,image_url:s.image_url||'',created_at:new Date().toISOString()};db.events.push(event);db[resource][idx]={...s,status:'approved',admin_notes:b.admin_notes||'',approved_event_id:event.id,reviewed_at:new Date().toISOString()};write(db);return send(res,200,db[resource][idx])}if(action==='reject'){db[resource][idx]={...db[resource][idx],status:'rejected',admin_notes:b.admin_notes||'',reviewed_at:new Date().toISOString()};write(db);return send(res,200,db[resource][idx])}}
if(req.method==='GET'&&!rid){let list=[...db[resource]];if(resource==='news')list=list.sort((a,b)=>String(b.created_at||'').localeCompare(String(a.created_at||'')));return send(res,200,list)}if(req.method==='GET'&&rid){const item=db[resource].find(x=>x.id===rid);return item?send(res,200,item):send(res,404,{error:'Item não encontrado'})}
if(req.method==='POST'&&!rid){if(resource!=='event-submissions'&&!admin(req))return send(res,401,{error:'Não autorizado'});const b=await body(req);const item={...b,id:id(),created_at:new Date().toISOString()};if(resource==='event-submissions')item.status='pending';db[resource].push(item);write(db);return send(res,201,item)}if(req.method==='PUT'&&rid){if(!admin(req))return send(res,401,{error:'Não autorizado'});const i=db[resource].findIndex(x=>x.id===rid);if(i<0)return send(res,404,{error:'Item não encontrado'});const b=await body(req);db[resource][i]={...db[resource][i],...b,id:rid,updated_at:new Date().toISOString()};write(db);return send(res,200,db[resource][i])}if(req.method==='DELETE'&&rid){if(!admin(req))return send(res,401,{error:'Não autorizado'});const i=db[resource].findIndex(x=>x.id===rid);if(i<0)return send(res,404,{error:'Item não encontrado'});db[resource].splice(i,1);write(db);return send(res,200,{ok:true})}return send(res,405,{error:'Método não permitido'})}catch(e){console.error(e);return send(res,500,{error:e.message||'Erro interno'})}});server.listen(PORT,()=>console.log(`Sumare API em http://localhost:${PORT}`));
function loadEnv(file){if(!fs.existsSync(file))return;for(const line of fs.readFileSync(file,'utf8').split(/\r?\n/)){const m=line.match(/^\s*([A-Z0-9_]+)=(.*)\s*$/);if(m&&!process.env[m[1]])process.env[m[1]]=m[2]}}
